[msx] test Started org.apache.hadoop.hdfs.server.namenode.TestEditLog#testFailedOpen[1]
[msx] unitTestCounterInClass = 0
2020-03-14 07:29:11,448 [main] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
[msx] test Failure org.apache.hadoop.hdfs.server.namenode.TestEditLog#testFailedOpen[1]
[msx] writeFile testName = org.apache.hadoop.hdfs.server.namenode.TestEditLog#testFailedOpen[1]
[msx] failed
[msx] failureMessage: Did no throw exception on only having a bad dir
[msx] stackTrace: java.lang.AssertionError: Did no throw exception on only having a bad dir
2020-03-14 07:29:11,915 [main] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 07:29:11,917 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] test Finished org.apache.hadoop.hdfs.server.namenode.TestEditLog#testFailedOpen[1]
[msx] writeFile testName = org.apache.hadoop.hdfs.server.namenode.TestEditLog#testFailedOpen[1]
[msx] Info : file existed /root/parameter_test_controller/shared/test_results/org.apache.hadoop.hdfs.server.namenode.TestEditLog#testFailedOpen[1]
[msx] succeed
[msx] reset performed
[msx] all testRunFinished
